Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
   # this line to give the VM a 50GB disk
  config.vm.disk :disk, size: "50GB", primary: true
  config.vm.hostname = "gitlab-server"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
    vb.cpus = 2
    vb.name = "gitlab-server"
  end
end