from datetime import datetime
from app.db import db

class Order(db.Model):
    __tablename__ = 'orders'

    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True,
        doc="Unique order ID (auto-generated by PostgreSQL)"
    )

    user_id = db.Column(
        db.String(100),
        nullable=False,
        doc="Customer/User ID who placed this order"
    )

    number_of_items = db.Column(
        db.String(10),
        nullable=False,
        doc="Number of movie items/copies in this order"
    )

    total_amount = db.Column(
        db.String(50),
        nullable=False,
        doc="Total cost of the order in currency units"
    )

    created_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow,
        doc="Timestamp when order was received and processed"
    )

    def to_dict(self):
        return {
            'id': self.id,
            'user_id': self.user_id,
            'number_of_items': self.number_of_items,
            'total_amount': self.total_amount,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }

    def __repr__(self):
        return f"<Order {self.id}>"